group=io.hevo
version=0.1.0-SNAPSHOT
gradleBomVersion=1.1.0
connectorFrameworkVersion=1.23.0
# Enable Gradle Configuration Cache
org.gradle.configuration-cache=true
# Gradle build properties
org.gradle.jvmargs=-Xms1024m -Xmx1024m
# disable aws sdk v1 announcement
aws.java.v1.disableDeprecationAnnouncement=true
